name: "test_extra_gradient_10x10"
game:
  generator: "random"
  num_players: 2
  action_sizes: [10, 10]
  utility_range: [-1.0, 1.0]
dynamic:
  algorithm: "extra_gradient"
  eta: 0.05
execution:
  compile: true
